version: '3'
services:
  # ROUTERS
  router1:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongos --configdb "config_servers/mongoindocker_config1_1:27019, mongoindocker_config2_1:27019, mongoindocker_config3_1:27019"
    ports:
      - "127.0.0.1:27117:27017"
    volumes:
      - ./scripts/router:/tmp/scripts
  router2:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongos --configdb "config_servers/mongoindocker_config1_1:27019, mongoindocker_config2_1:27019, mongoindocker_config3_1:27019"
    ports:
      - "127.0.0.1:27118:27017"
    links:
      - router1
  router3:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongos --configdb "config_servers/mongoindocker_config1_1:27019, mongoindocker_config2_1:27019, mongoindocker_config3_1:27019"
    ports:
      - "127.0.0.1:27119:27017"
    links:
      - router2

  # CONFIG SERVERS
  config1:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongod --configsvr --replSet config_servers
    expose:
      - "27019"
    volumes:
      - ./scripts/config:/tmp/scripts
    links:
      - shard_rs1_1
      - shard_rs1_2
      - shard_rs1_3
  config2:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongod --configsvr --replSet config_servers
    expose:
      - "27019"
    links:
      - config1
  config3:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongod --configsvr --replSet config_servers
    expose:
      - "27019"
    links:
      - config2

  # SHARDS
  shard_rs1_1:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongod --shardsvr --replSet rs1
    volumes:
      - ./scripts/shard:/tmp/scripts
    links:
        - shard_rs1_2
        - shard_rs1_3
  shard_rs1_2:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongod --shardsvr --replSet rs1
  shard_rs1_3:
    image: mongo:3.2.9
    entrypoint: /usr/bin/mongod --shardsvr --replSet rs1

